### ISSUE TITLE
error searching pip has no attribute get_installed_distributions

### ISSUE THREAD

**Issue by MaximilianoRom7** [balzss/yip#11]
I am using python3 and Manjaro Linux, I tried to upgrade the pip package and create a new virtualenv and the problem persists.

<pre>
/home/skyline: yip search go
 |----------------------------------------------------------------------------------------------------| 0.0% Traceback (most recent call last):
  File "/usr/bin/yip", line 434, in <module>
    installed_packages = get_installed()
  File "/usr/bin/yip", line 152, in get_installed
    return {i.key: i.version for i in pip.get_installed_distributions()}
AttributeError: module 'pip' has no attribute 'get_installed_distributions'
</pre>

**Comment by MaximilianoRom7** [comment]
found the solution, it seams that yip works if the pip version is 9.0.3 or lower, but I had installed the last version to this date that is pip 18.0, so when I downgrade to pip==9.0.3 everything worked fine.

<pre>
/home/skyline: pip show pip
Name: pip
Version: 9.0.3
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /usr/lib/python3.6/site-packages
Requires:

</pre>

**Comment by balzss** [comment]
Hi, thanks for reporting this issue. This seems to be the same problem that was addressed in #9 which I wanted to test and merge for quite some time now but am a bit overwhelmed with work atm. Will try to get around it eventually. Thanks.

**Comment by balzss** [comment]
Closing as #9 was merged. Reopen the issue if that doesn't solve the problem.

**Comment by kiloforce** [comment]
If issue #17 is eventually resolved, the PyPI package should be updated.
